# Generated by Django 4.2.5 on 2025-12-01 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('vote', '0001_initial'), ('vote', '0002_auto_20161229_1022'), ('vote', '0003_vote_action'), ('vote', '0004_auto_20170110_1150'), ('vote', '0005_alter_vote_id')]

    initial = True

    dependencies = [
        ('auth', '__first__'),
        ('contenttypes', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('object_id', models.PositiveIntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('action', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'unique_together': {('user_id', 'content_type', 'object_id', 'action')},
                'index_together': {('content_type', 'object_id')},
            },
        ),
    ]
