# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-29 02:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='vote',
            index_together=set([('content_type', 'object_id')]),
        ),
    ]
