# Generated by Django 5.0.6 on 2025-05-21 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('vote', '0004_auto_20170110_1150'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='vote',
            new_name='vote_vote_content_a520b4_idx',
            old_fields=('content_type', 'object_id'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('user_id', 'content_type', 'object_id', 'action'), name='unique_vote'),
        ),
    ]
