# Generated by Django 4.2.5 on 2025-04-17 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_auto_20170110_1150'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='vote',
            new_name='vote_vote_content_a520b4_idx',
            old_fields=('content_type', 'object_id'),
        ),
    ]
