# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  pull_request:
    types:
      - opened

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        django-version: [2.0, 3.0]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -q Django==${{ matrix.django-version }} flake8 coverage djangorestframework
      - name: Lint with flake8
        run: |
          flake8 --exclude vote/migrations/* vote
      - name: Test with coverage
        run: |
          coverage run runtests.py
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
